# Generated by Django 2.0.3 on 2018-03-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180326_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createed_time',
            new_name='created_time',
        ),
    ]
